@baseUrl =  http://localhost:5000
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OWIzYjkwMTFlNmIwN2Y4MDFjYmQzZCIsImxvZ2luIjoiaWFzaGNodWsyIiwiZW1haWwiOiJpYXNoY2h1azIuZGV2QGhtYWlsLmNvbSIsImRldmljZUlkIjoiZWE0ODA2ODgtMDZlOS00MjdlLWE3MjItNzhhOTNhYTNlN2RjIiwiaWF0IjoxNjg3OTAyMTc0LCJleHAiOjE2ODc5MDI1MzR9.i_c_sU6nIDbFGc8MK1Icv_XY_qrPaJrQEJGrWRm41iY

## Login
POST {{baseUrl}}/auth/login HTTP/1.1
Content-Type: application/json

{
  "loginOrEmail": "iashchuk",
  "password": "123456"
}

###


## Get user info
GET {{baseUrl}}/auth/me HTTP/1.1
Authorization: {{token}}
Content-Type: application/json

###

## Create new user
POST {{baseUrl}}/auth/registration HTTP/1.1
Content-Type: application/json

{
  "login": "test2",
  "password": "123456",
  "email": "test2@local.io"
}

###

## Registration Confirmation
POST {{baseUrl}}/auth/registration-confirmation HTTP/1.1
Content-Type: application/json

{
  "code": "b8dee5b0-781f-4b34-b124-2952a73a455d"
}

### 

## Registration Email Resending
POST {{baseUrl}}/auth/registration-email-resending HTTP/1.1
Content-Type: application/json

{
  "email": "221box@list.ru"
}

###

## Password Recovery
POST {{baseUrl}}/auth/password-recovery HTTP/1.1
Content-Type: application/json

{
  "email": "221box@list.ru"
}

###

## New Password
POST {{baseUrl}}/auth/new-password HTTP/1.1
Content-Type: application/json

{
  "newPassword": "123456",
  "recoveryCode": "d0f65420-4892-495a-bed9-6b05c48ff43d"
}

###


## Refresh Token
POST {{baseUrl}}/auth/refresh-token HTTP/1.1
Content-Type: application/json
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1OWMxYmJmMDQzZmY1ODhlZGY1ZmIwMiIsImxvZ2luIjoiaWFzaGNodWsiLCJlbWFpbCI6IjIyMWJveEBsaXN0LnJ1IiwiZGV2aWNlSWQiOiI1NWQ4NWIwOS05YjNkLTRmMGItYTVkZC04NGExYmM4M2FhNTUiLCJpYXQiOjE3MDQ3MzIwNjAsImV4cCI6MTcwNDczNDA2MH0.fmbAitDmZMbQErvTMgBYwYJ99z_YXRic0jP3hWN2-pM

###

## Logout
POST {{baseUrl}}/auth/logout HTTP/1.1
Content-Type: application/json
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMzVlZTQ0LThjZDAtNDU4Mi1iYTk5LWI0NjEyYWUwZTAzMyIsImxvZ2luIjoibGctNjQxMzQ3IiwiZW1haWwiOiJlbWFpbDY0MTM0N0BnZy5jb20iLCJkZXZpY2VJZCI6IjY4MjU3NzllLWUzZDktNGY5Mi1iYjYwLTU3Y2Y2NjhlNGQ4NiIsImlhdCI6MTcwNTY3MjY3MCwiZXhwIjoxNzA1NjcyNjkwfQ.OhbqqxcFQwZcT5TSZd7ZyY9LthGc4d5hxzz-gu5qGA4

###

## Get test sql
GET {{baseUrl}}/auth/test HTTP/1.1
Content-Type: application/json

###
