@baseUrl =  http://localhost:5000 
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDdhMjU0ZjQxYTkyMjY4YTAxYzExZGIiLCJlbWFpbCI6Imlhc2hjaHVrLmRldkBobWFpbC5jb20iLCJpYXQiOjE2ODU3NDIyODgsImV4cCI6MTY4NTc0NTI4OH0.CjliGQ3El1iBuliFM6dp2Yxd4zgOzg4SZ9XuXbe1CF0


## Login
POST {{baseUrl}}/auth/login HTTP/1.1
Content-Type: application/json

{
  "loginOrEmail": "iashchuk2",
  "password": "123456"
}

###


## Get user info
GET {{baseUrl}}/auth/me HTTP/1.1
Authorization: {{token}}
Content-Type: application/json

###

## Create new user
POST {{baseUrl}}/auth/registration HTTP/1.1
Content-Type: application/json

{
  "login": "iashchuk2",
  "password": "123456",
  "email": "iashchuk2.dev@hmail.com"
}

###

## Registration Confirmation
POST {{baseUrl}}/auth/registration-confirmation HTTP/1.1
Content-Type: application/json

{
  "code": "a22b63bd-16f3-45d3-bfa4-ff7e9c384001"
}

### 

## Registration Email Resending
POST {{baseUrl}}/auth/registration-email-resending HTTP/1.1
Content-Type: application/json

{
  "email": "iashchuk@outlook.com"
}

###

## Password Recovery
POST {{baseUrl}}/auth/password-recovery HTTP/1.1
Content-Type: application/json

{
  "email": "221box@list.ru"
}

###

## New Password
POST {{baseUrl}}/auth/new-password HTTP/1.1
Content-Type: application/json

{
  "newPassword": "123456",
  "recoveryCode": "d0f65420-4892-495a-bed9-6b05c48ff43d"
}

###


## Refresh Token
POST {{baseUrl}}/auth/refresh-token HTTP/1.1
Content-Type: application/json
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDZiZWQ5Yjc3MWY1YTQzMzE4YzcyYjEiLCJlbWFpbCI6IjIyMWJveEBsaXN0LnJ1IiwiaWF0IjoxNjg0ODczNzM4LCJleHAiOjE2ODQ4NzQ0NTh9.eVRT8IVy458viajzhtiSc-EJkzBrLkMiGSrvnBlILVg

###

## Logout
POST {{baseUrl}}/auth/logout HTTP/1.1
Content-Type: application/json
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDZiZWQ5Yjc3MWY1YTQzMzE4YzcyYjEiLCJlbWFpbCI6IjIyMWJveEBsaXN0LnJ1IiwiaWF0IjoxNjg0ODc0NTg3LCJleHAiOjE2ODQ4NzUzMDd9.q8MosDWqJXEw4iRcPIzWZHscH7M4SVz3B9BOMVie0sQ

###
