@baseUrl =  http://localhost:5000 
@token = 
@id = 
@paginationParams = 


## Add new user to the system
POST {{baseUrl}}/users HTTP/1.1
Authorization: Basic YWRtaW46cXdlcnR5
Content-Type: application/json

{
  "login": "admin02",
  "password": "123456",
  "email": "admin02@local.io"
}

###

## Returns all users
GET {{baseUrl}}/users?{{paginationParams}} HTTP/1.1
Content-Type: application/json

###

## Delete user specified by id
DELETE {{baseUrl}}/users/655123edf839fa28c42b763b HTTP/1.1
Authorization: Basic YWRtaW46cXdlcnR5

###