@baseUrl =  http://localhost:5000 
@token = 
@id = 
@paginationParams = 


## Create new user
POST {{baseUrl}}/users HTTP/1.1
Content-Type: application/json

{
  "login": "admin332e",
  "password": "123456",
  "email": "admin332e@local.io"
}

###

## Get user list with pagination
GET {{baseUrl}}/users?{{paginationParams}} HTTP/1.1
Content-Type: application/json

###

## Delete user by id
DELETE {{baseUrl}}/users/646d650f4cac3af2bf0baadf HTTP/1.1
Authorization: Basic YWRtaW46cXdlcnR5

###