@baseUrl =  http://localhost:3000 
@token = 
@id = 
@paginationParams = pageNumber=1&pageSize=10&sortBy=login


## Create new user
POST {{baseUrl}}/users HTTP/1.1
Content-Type: application/json

{
  "login": "admin",
  "password": 123456,
  "email": "admin@local.io"
}

###

## Get user list with pagination
GET {{baseUrl}}/users?{{paginationParams}} HTTP/1.1
Content-Type: application/json

###

## Delete user by id
DELETE {{baseUrl}}/users/{{id}} HTTP/1.1

###