@baseUrl =  http://localhost:5000
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDdhNzU2NjRlZjM4ZWQzMTIzMzAwMzIiLCJlbWFpbCI6Imlhc2hjaHVrMi5kZXZAaG1haWwuY29tIiwiaWF0IjoxNjg1NzQ3MDUxLCJleHAiOjE2ODU3NTAwNTF9.B43QhmLOAV-L-IE6Vj47iW2JyaD5HMCTRqfOCL0gDVY
@id = 

## Get devices
GET {{baseUrl}}/security/devices HTTP/1.1
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImEzYzI0MGZjLWRlZTUtNDA4Yi04NjBlLWFjOTUwNDIyNDliNiIsImxvZ2luIjoiaWFzaGNodWsiLCJlbWFpbCI6IjIyMWJveEBsaXN0LnJ1IiwiZGV2aWNlSWQiOiIwYjQ1OWY0Mi01ZDFiLTQ4YTgtODg4Mi1mYjJhNmJhZGU4NTgiLCJpYXQiOjE3MDU2NzIxODMsImV4cCI6MTcwNTY3MjIwM30.TfZoNznbs7tqwnnCN1vAMN-2yUUd_2Djvhmo2kZexWg

###


## Delete devices
DELETE {{baseUrl}}/security/devices HTTP/1.1
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImEzYzI0MGZjLWRlZTUtNDA4Yi04NjBlLWFjOTUwNDIyNDliNiIsImxvZ2luIjoiaWFzaGNodWsiLCJlbWFpbCI6IjIyMWJveEBsaXN0LnJ1IiwiZGV2aWNlSWQiOiIwZDFhYTI4MC05YTBiLTQ0NWEtYTc3ZC1mNmU5MWU4MmZiNWQiLCJpYXQiOjE3MDU2NzIyNjAsImV4cCI6MTcwNTY3NDI2MH0.34EiEIY2xxZZsFBaUn2EwRdPH0gZdmptqwiHFlRVCto

###