@baseUrl =  http://localhost:5000
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDdhNzU2NjRlZjM4ZWQzMTIzMzAwMzIiLCJlbWFpbCI6Imlhc2hjaHVrMi5kZXZAaG1haWwuY29tIiwiaWF0IjoxNjg1NzQ3MDUxLCJleHAiOjE2ODU3NTAwNTF9.B43QhmLOAV-L-IE6Vj47iW2JyaD5HMCTRqfOCL0gDVY
@id = 

## Get devices
GET {{baseUrl}}/security/devices HTTP/1.1
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0N2I3ODZkZDg5OTU1YjY2ODI5OWExOSIsImxvZ2luIjoiaWFzaGNodWsyIiwiZW1haWwiOiJpYXNoY2h1azIuZGV2QGhtYWlsLmNvbSIsImlhdCI6MTY4NTgxMzM2MSwiZXhwIjoxNjg1ODIwNTYxfQ.xpy6rkPyGB1ATvVvjTlNmtNwI7MiML7tducBl5AGX5g

###


## Delete devices
DELETE {{baseUrl}}/devices HTTP/1.1
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDZiZWQ5Yjc3MWY1YTQzMzE4YzcyYjEiLCJlbWFpbCI6IjIyMWJveEBsaXN0LnJ1IiwiaWF0IjoxNjg0ODczNzM4LCJleHAiOjE2ODQ4NzQ0NTh9.eVRT8IVy458viajzhtiSc-EJkzBrLkMiGSrvnBlILVg

###