@baseUrl =  http://localhost:5000
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0N2IyODg5NGI1YzA5MTVmOTg2YmY1NCIsImxvZ2luIjoiaWFzaGNodWsyIiwiZW1haWwiOiJpYXNoY2h1azIuZGV2QGhtYWlsLmNvbSIsImlhdCI6MTY4NTc5MjkwOSwiZXhwIjoxNjg1Nzk1OTA5fQ.2wIuf0nue_TdzyMZNECC-Jud4MxhRhSo7JH1-aXLudA

@id = 347992af-20d8-4bea-a1ba-5e701a580c98

@paginationParams = ""

## Create new blog
POST {{baseUrl}}/blogs HTTP/1.1
Content-Type: application/json
Authorization: Basic YWRtaW46cXdlcnR5

{
  "name": "My memo",
  "description": "About new react features",
  "websiteUrl": "https://nestjs-template.vercel.app"
  }

###

## Update blog by id
PUT {{baseUrl}}/blogs/{{id}} HTTP/1.1
Content-Type: application/json
Authorization: Basic YWRtaW46cXdlcnR5

{
  "name": "My memo 2",
  "description": "About new react features",
  "websiteUrl": "https://nestjs-template.vercel.app"
}

###

## Get blog by id
GET {{baseUrl}}/blogs/{{id}} HTTP/1.1
Content-Type: application/json

###

## Get blog list with pagination
GET {{baseUrl}}/blogs?{{paginationParams}} HTTP/1.1
Content-Type: application/json

###

## Delete blog by id
DELETE {{baseUrl}}/blogs/{{id}} HTTP/1.1

###

## Get post list by blog
GET {{baseUrl}}/blogs/82d172e0-03e5-4dee-9f6b-e6d18ef79525/posts HTTP/1.1
Content-Type: application/json

###

## Create post by blog

POST {{baseUrl}}/blogs/82d172e0-03e5-4dee-9f6b-e6d18ef79525/posts HTTP/1.1
Content-Type: application/json
Authorization: Basic YWRtaW46cXdlcnR5

{
  "title": "New Effect 2023",
  "shortDescription": "Incredible effect in React",
  "content": "https://reactjs.ru"
}

###
